#!/bin/bash

if [ "$1" == "COMPILE" ]; then
    . config
    cd CHIP-linux
    cpuCores=$(grep -c ^processor /proc/cpuinfo)

    # compile
    make -j$cpuCores ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf-
    
    # install modules
    make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- INSTALL_MOD_PATH=$WORKSPACE/bin/ modules_install
    exit
fi

. config
. functions.sh.inc

schrootBeginSession || exit $?
schroot -r -c $SESSION_NAME -- $0 COMPILE || exit $?
